#! /bin/sh

### BEGIN INIT INFO
# Provides:          piwalltile
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

DIR=/etc/init.d
DAEMON=$DIR/starttile.sh
DAEMON_NAME=piwalltile

DAEMON_USER=pi
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting  $DAEMON_NAME daemon"
    start-stop-daemon --start --pidfile $PIDFILE --make-pidfile $PIDFILE --user $DAEMON_USER --exec $DAEMON
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping  $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
